### ISSUE TITLE
外部APIの結果をキャッシュする

### ISSUE THREAD

**Issue by pyama86** [pepabo/k8s-github-auth#2]
Githubに対するapiリクエストを認証の都度やっているので、キャッシュしてはどうだろうかと思ったのですがいかがでしょうか？

ポジティブとネガティブ両方しきい値変えられるように実装すると良いかなぁと思っている。

**Comment by takaishi** [comment]
以下の理由より、ひとまずはキャッシュの実装は不要そうなのでクローズします。やはり負担だということになればリオープンして再度検討します

* apiserver側で認証のキャッシュを行っている
* 本issueの要因となったのはJWTがトークンとして渡ってきていたこと。https://github.com/takaishi/k8s-github-auth/pull/5 でJWTだとGithubへリクエストせずにrejectするように修正したのでk8s-github-authでキャッシュしなくても大丈夫になったと思われる

**Comment by pyama86** [comment]
あざます〜
